/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "myclock.h"
#include "i2c.h"

char data[2] = {0x01,0x02};
int main(void)
{

	systick_init();
	i2c_init(1,i2c_SM);


	while(1)
	{
		i2c_write(1,0x78,data);
		DelayMs(10);
	}

}
